import type { Metadata } from 'next';
import './globals.css';
import { Roboto } from 'next/font/google';
import Navbar from '@/components/Navbar';

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${roboto.className} antialiased selection:text-white selection:bg-secondary overflow-x-hidden`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
